name: Rocnikovka
version: '${project.version}'
main: cz.christian.rocnikovka.Main
api-version: 1.18

commands:
  pluginEnable:
    description: Zapne plugin
    usage: /pluginEnable

  storyEnable:
    description: Zapne příběh
    usage: /storyEnable

  reloadPlugin:
    description: Reloadne plugin
    usage: /reloadPlugin